spring.application.name=SpringBootWebFlux

#server.port=3713
#mysql database configuration
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/mlamarch2
#spring.datasource.username=root
#spring.datasource.password=root@39

#spring.datasource.hikari.connection-timeout=60000
#spring.datasource.hikari.maximum-pool-size=5

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.r2dbc.url=r2dbc:mysql://localhost:3306/mlamarch2
spring.r2dbc.username=root
spring.r2dbc.password=root@39

server.port= 3713

debug=true

